// Types
export const GET_USER = 'GET_USER';
export const GET_USER_PENDING = 'GET_USER_PENDING';
export const GET_USER_FULFILLED = 'GET_USER_FULFILLED';
export const GET_USER_REJECTED = 'GET_USER_REJECTED';

export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLES_PENDING = 'GET_ARTICLES_PENDING';
export const GET_ARTICLES_FULFILLED = 'GET_ARTICLES_FULFILLED';
export const GET_ARTICLES_REJECTED = 'GET_USER_REJECTED';

export const GET_ERRORS = 'GET_ERRORS';

export const TOGGLE_MENU = 'TOGGLE_MENU';
